services:
  postgres:
    container_name: "bookrab_db"
    image: "postgres:17.2"
    restart: always
    ports:
      - "5432:5432"
    environment:
      - "POSTGRES_USER=bookrab"
      - "POSTGRES_DB=bookrab_db"
      - "POSTGRES_PASSWORD=bookStrongPass"
